server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /pokemon-team/v1
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
  pattern:
    console: "[%thread][%highlight(%-5level)][%blue(%d{yyyy-MM-dd HH:mm:ss})][%blue(%X{requestId})][%green(%logger{40})] - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "info,health"
spring:
  data:
    mongodb:
      database: pokemon-team-mongodb
      port: 27017
      host: localhost
pokeapi:
  urlPokemon: ${POKEAPI_URL:https://pokeapi.co/api/v2/pokemon/}
  urlAbilities:  ${POKEAPI_URL:https://pokeapi.co/api/v2/ability/}
