version: "3"
services:
  postgres:
    image: postgres:10.5
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  pact_broker:
      image: dius/pact-broker:2.27.2-1
      do:
        - "9292:9292"
      links:
        - postgres
      environment:
        PACT_BROKER_DATABASE_USERNAME: postgres
        PACT_BROKER_DATABASE_PASSWORD: password
        PACT_BROKER_DATABASE_HOST: postgres
        PACT_BROKER_DATABASE_NAME: postgres
        PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http https
  mongo:
    image: mongo
    container_name: pokemon-dream-team
    environment:
       - MONGO_INITDB_DATABASE= pokemon-team-mongodb
    ports:
      - 27017:27017
    networks:
      - spring-mongo-net
networks:
 spring-mongo-net:
              driver: bridge
volumes:
  postgres-volume: