version: '3'
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: blue
      ME_CONFIG_BASICAUTH_PASSWORD: blue
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: red
      ME_CONFIG_MONGODB_ADMINPASSWORD: red
    links:
      - mongo
    networks:
      - mongo-compose-network